services:

  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - db-test

  app:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/transactionsapp
    container_name: transactionsapp
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mysqlvolume:

networks:
  db-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "111.111.10.0/24"