spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_database?useSSL=false&serverTimezone=UTC
    username: app_user
    password: app_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect